#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Pollar.Resource", IsApplication=true)]

namespace Pollar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int QuestionCell = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int barChart1 = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int btnAns1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnAns2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnAns3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btnAns4 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int btnAsk = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int btnBack = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int btnEnter = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btnMine = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int btnReturn = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int fldAns1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int fldAns2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int fldAns3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fldAns4 = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int fldQuestion = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int fldRoomID = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int lstQuestions = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int textViewQuestion = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int textViewRoomID = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int txtException = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int txtQuestion = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int txtRoomID = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Answer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Ask = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MyQuestions = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QuestionCellView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int QuestionData = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
